# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TAXc88Z0oYuEtVz_finybLoG9eBDTPOT
"""

!pip install requests
!pip install selenium
!apt install chromium-chromedriver
!cp /usr/lib/chromium-browser/chromedriver /usr/bin
import requests
import webbrowser
import selenium
from selenium import webdriver  
from selenium.webdriver.common.keys import Keys  
from selenium import webdriver
import sys
sys.path.insert(0,'/usr/lib/chromium-browser/chromedriver')
chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument('--headless')
chrome_options.add_argument('--no-sandbox')
chrome_options.add_argument('--disable-dev-shm-usage')


result = requests.get('https://www.googleapis.com/books/v1/volumes?q=user+story+mapping')

# converting data response to json format and storing it as python dictionary
d1 = dict(result.json())

isbn10=[] # storing isbn of 10 digit format
isbn13=[] # storing isbn of 13 digit format

# Retrieving isbn from dictionary and storing it in respective lists
for i in range(8):
  a= d1['items'][i]['volumeInfo']['industryIdentifiers'][0]['identifier']
  b= d1['items'][i]['volumeInfo']['industryIdentifiers'][1]['identifier'] 
  if len(a)==10:
    isbn10.append(a)
    isbn13.append(b)
  else:
    isbn10.append(b)
    isbn13.append(a)
a=d1['items'][9]['volumeInfo']['industryIdentifiers'][0]['identifier']
b=d1['items'][9]['volumeInfo']['industryIdentifiers'][1]['identifier']
if len(a)==10:
  isbn10.append(a)
  isbn13.append(b)
else:
  isbn10.append(b)
  isbn13.append(a)

wd = webdriver.Chrome('chromedriver',chrome_options=chrome_options)

wd.get('https://www.google.com/')

# Entering isbn to search box on google website
wd.find_element_by_name("q").send_keys(a)  # instead of 'a' can give any isbn number stored in list
buttonm= wd.find_element_by_name("btnK")
wd.implicitly_wait(10)

#hitting button
buttonm.click()